### ISSUE TITLE
Can't use with require()

### ISSUE THREAD

**Issue by mathisonian** [Richienb/url-exist#31]
Hi @Richienb, thanks for this module! 

I am running into an issue running in a node.js environment where we use the standard `require()`  syntax to import modules, however if I try to add this package I get the error `require() of ES modules is not supported.`

My understanding of ES modules was that these are mainly for browser-based modules, not node.js - would you be willing to update this package so it works with standard require? I believe this is happening because of the `"type": "module"` that is set in [`package.json`](https://github.com/Richienb/url-exist/blob/master/package.json#L11).

**Comment by Richienb** [comment]
Starting from Node.js 12, ESM will be supported (without flags). This allows the Node.js and Web ecosystem to come together with a single module system. 

I would highly recommend that you migrate your project to use ESM or use alternatively use `url-exist@2.0.2` if you wish to stay on the CJS system. If you use a bundler like Rollup or Webpack, you can configure it to resolve `import` statements and generate bundles that insert the referenced code directly.

https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77

<blockquote><img src="https://miro.medium.com/max/1200/1*x1hibXxUHdyNRZmwaIGUnQ.png" width="48" align="right"><div><img src="https://miro.medium.com/fit/c/256/256/1*g0Jo0SxlTq7J6D5kAwzF4A.png" height="14"> Medium</div><div><strong><a href="https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77">Get Ready For ESM</a></strong></div><div>JavaScript Modules will soon be a reality for Node.js package maintainers.</div></blockquote>

**Comment by Multi-Thinker** [comment]
problem still exist, using node 14

**Comment by Richienb** [comment]
@Multi-Thinker Did you read my reply?
