### ISSUE TITLE
False , Even image exist in url-exist@2.0.2

### ISSUE THREAD

**Issue by lalitmohan-st** [Richienb/url-exist#32]
https://cdn-sliders.eneba.com/QzxlwqBtARNYe7vb3hFE8XiV5NgPrtNcLGT7ZV2bAIU.jpeg

I am not sure, what I am doing wrong

**Comment by Richienb** [comment]
Are you running the function from Node.js or in the browser?

**Comment by lalitmohan-st** [comment]
> Are you running the function from Node.js or in the browser?

Yes, I am running the function into node js. There is a problem with a specific image. Here you can see the snipped


    `const urlExist = require('url-exist');   

    let isValidImage = await urlExist(image);

    if(!isValidImage){
      image = `${config.s3URL}placeholder/group-7@2x.png`;
    }
  `

**Comment by Richienb** [comment]
It appears this problem is fixed in v3, try upgrading.

**Comment by lalitmohan-st** [comment]
> It appears this problem is fixed in v3, try upgrading.

I have to use in ES5 :(

**Comment by Richienb** [comment]
CommonJS is being phased out. Here's how to migrate to ESM:

https://github.com/sindresorhus/meta/discussions/15

**Comment by lalitmohan-st** [comment]
> CommonJS is being phased out. Here's how to migrate to ESM:
> 
> [sindresorhus/meta#15](https://github.com/sindresorhus/meta/discussions/15)

I will check it, you can close the ticket if it already resolved in a newer version
