### ISSUE TITLE
await outside async

### ISSUE THREAD

**Issue by rogueturnip** [Richienb/url-exist#33]
I'm seeing the following error when using the module.  This happens when just the import statement is added.
I'm running on Node 14.

ERROR in/tracking-api/node_modules/ky-universal/index.js 29:30
Module parse failed: Cannot use keyword 'await' outside an async function (29:30)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| if (!globalThis.ReadableStream) {
|       try {
>               globalThis.ReadableStream = await import('web-streams-polyfill/ponyfill/es2018');
|       } catch {}
| }
 @ /alana-tracking-api/node_modules/url-exist/index.js 2:0-29 13:24-26
 @ /alana-tracking-api/handlers/generateLink.js

**Comment by Richienb** [comment]
If you're using Webpack, you might need to configure the `experiments` option to include `topLevelAwait`. https://webpack.js.org/configuration/experiments/
