### ISSUE TITLE
Please switch from using url-regex to url-regex-safe

### ISSUE THREAD

**Issue by mindphluxnet** [Richienb/url-exist#35]
url-regex has security issues:

https://www.npmjs.com/advisories/1550

and since its no longer updated it's advised to use 

https://www.npmjs.com/package/url-regex-safe

instead.

**Comment by Richienb** [comment]
https://github.com/niftylettuce/url-regex-safe/issues/9

**Comment by Richienb** [comment]
False alarm, this package doesn't use url-regex.
